env:
  global:
    - CC_TEST_REPORTER_ID=cbdd9ab76e5d36bb5563d9ff09fb38f90f7481d5ed29f7dfb6ff0c94b70a106e

language: node_js

node_js:
  - "stable"

install:
  - npm ci

cache:
  directories:
    - node_modules

before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script:
  - npm test

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT